"""Scoped Copilot credentials in the existing encrypted subscription table.

Trusted synchronous service API: callers establish provider identity and payer
authorization before calling. No GitHub validation, implicit pool selection,
durable lease, or runtime revocation is performed here. A read is a snapshot;
consumers must revalidate it before dispatch and while a runtime remains live.
"""

from functools import wraps
import json
import time
import uuid

from core.layers.copilot.credentials import (
    AccountScopeKind, CopilotAccountScope, CopilotCredential,
    CredentialKind, CredentialUnavailableError,
)
from storage.credential_store import decrypt_secret, encrypt_secret
from storage.pg import get_conn
from storage.subscription_store import _now, _row_to_dict


_AUTH_TYPES = {
    CredentialKind.USER_TOKEN: "copilot_user_token",
    CredentialKind.INSTALLATION_TOKEN: "copilot_installation_token",
}
_SELECT = """SELECT s.*, u.role AS owner_role
             FROM execution_layer_subscriptions s
             JOIN users u ON u.sub = s.owner_sub WHERE s.id = %s"""


def _sanitized(operation):
    @wraps(operation)
    def call(*args, **kwargs):
        try:
            return operation(*args, **kwargs)
        except Exception:
            # Database/JSON exceptions may contain credential parameters. Do
            # not chain them into a public error or retain them as its context.
            pass
        raise CredentialUnavailableError("Copilot account credential is unavailable")
    return call


def _identity(value):
    return isinstance(value, str) and bool(value) and value == value.strip() and value.isprintable()


def _encode(credential):
    return encrypt_secret(json.dumps({"copilot": {
        "version": 1, "principal_id": credential.principal_id,
        "revision": credential.revision, "kind": credential.kind.value,
        "token": credential.token, "expires_at": credential.expires_at,
    }}))


def _decode(row):
    if not row or row["layer"] != "copilot-cli" or row["provider"] != "github":
        raise CredentialUnavailableError()
    blob = json.loads(decrypt_secret(row["credential_data_enc"]))
    data = blob["copilot"]
    if (type(data) is not dict or type(data.get("version")) is not int
            or data["version"] != 1 or set(data) != {
                "version", "principal_id", "revision", "kind", "token", "expires_at",
            }):
        raise CredentialUnavailableError()
    kind = CredentialKind(data["kind"])
    if row["auth_type"] != _AUTH_TYPES[kind] or row["oauth_email"] != data["principal_id"]:
        raise CredentialUnavailableError()
    # Revisions generated by this store are UUIDs, never timestamps/counters.
    if str(uuid.UUID(data["revision"])) != data["revision"]:
        raise CredentialUnavailableError()
    return CopilotCredential(
        account_id=row["id"], principal_id=data["principal_id"], revision=data["revision"],
        kind=kind, token=data["token"], expires_at=data["expires_at"],
    )


@_sanitized
def create_account(owner_sub, principal_id, kind, token, expires_at,
                   use_personal=True, contribute_platform=False, label="") -> dict:
    """Create an explicitly owned account; shared contribution defaults off."""
    if (not _identity(owner_sub) or type(use_personal) is not bool
            or type(contribute_platform) is not bool or not isinstance(label, str)):
        raise CredentialUnavailableError()
    credential = CopilotCredential(
        account_id=str(uuid.uuid4()), principal_id=principal_id,
        revision=str(uuid.uuid4()), kind=kind, token=token, expires_at=expires_at,
    )
    credential.ensure_usable(time.time())
    encrypted = _encode(credential)
    with get_conn() as conn:
        owner = conn.execute("SELECT role FROM users WHERE sub = %s FOR SHARE", (owner_sub,)).fetchone()
        if not owner or (contribute_platform and owner["role"] != "admin"):
            raise CredentialUnavailableError()
        now = _now()
        row = conn.execute(
            """INSERT INTO execution_layer_subscriptions
               (id, layer, provider, auth_type, owner_sub, use_personal,
                contribute_platform, label, credential_data_enc, oauth_email,
                active_sessions, status, created_at, updated_at)
               VALUES (%s, 'copilot-cli', 'github', %s, %s, %s, %s, %s, %s,
                       %s, 0, 'active', %s, %s) RETURNING *""",
            (credential.account_id, _AUTH_TYPES[kind], owner_sub, use_personal,
             contribute_platform, label, encrypted, principal_id, now, now),
        ).fetchone()
        conn.commit()
        return _row_to_dict(row)


@_sanitized
def read_credential(account_id, scope, min_runway=0) -> CopilotCredential:
    """Read one selected account with current scope and owner eligibility."""
    if not _identity(account_id) or type(scope) is not CopilotAccountScope:
        raise CredentialUnavailableError()
    with get_conn() as conn:
        row = conn.execute(_SELECT, (account_id,)).fetchone()
        if not row or row["status"] != "active":
            raise CredentialUnavailableError()
        if scope.kind is AccountScopeKind.PERSONAL:
            allowed = row["owner_sub"] == scope.user_sub and row["use_personal"] is True
        else:
            allowed = row["contribute_platform"] is True and row["owner_role"] == "admin"
        if not allowed:
            raise CredentialUnavailableError()
        credential = _decode(row)
        credential.ensure_usable(time.time(), min_runway)
        return credential


@_sanitized
def replace_credential(account_id, owner_sub, expected_revision, principal_id,
                       kind, token, expires_at) -> CopilotCredential:
    """Owner-only compare-and-swap refresh; never revive a disabled account."""
    if not _identity(owner_sub) or not _identity(account_id):
        raise CredentialUnavailableError()
    with get_conn() as conn:
        row = conn.execute(_SELECT + " FOR UPDATE OF s", (account_id,)).fetchone()
        if not row or row["owner_sub"] != owner_sub:
            raise CredentialUnavailableError()
        old = _decode(row)
        if (old.revision != expected_revision or old.principal_id != principal_id
                or old.kind is not kind):
            raise CredentialUnavailableError()
        credential = CopilotCredential(
            account_id=account_id, principal_id=principal_id, revision=str(uuid.uuid4()),
            kind=kind, token=token, expires_at=expires_at,
        )
        credential.ensure_usable(time.time())
        conn.execute(
            """UPDATE execution_layer_subscriptions
               SET credential_data_enc = %s, updated_at = %s WHERE id = %s""",
            (_encode(credential), _now(), account_id),
        )
        conn.commit()
        return credential
