"""Scoped Copilot credentials in the existing encrypted subscription table.

Trusted synchronous service API: callers establish provider identity and payer
authorization before calling. No GitHub validation, implicit pool selection,
durable lease, or runtime revocation is performed here. A read is a snapshot;
consumers must revalidate it before dispatch and while a runtime remains live.
"""

from functools import wraps
import json
import re
import time
import uuid

from core.layers.copilot.credentials import (
    AccountScopeKind, CopilotAccountScope, CopilotCredential,
    CredentialKind, CredentialUnavailableError,
)
from storage.credential_store import decrypt_secret, encrypt_secret
from storage.pg import get_conn
from storage.subscription_store import _now, _row_to_dict


_AUTH_TYPES = {
    CredentialKind.USER_TOKEN: "copilot_user_token",
    CredentialKind.INSTALLATION_TOKEN: "copilot_installation_token",
}
_SELECT = """SELECT s.*, u.role AS owner_role
             FROM execution_layer_subscriptions s
             JOIN users u ON u.sub = s.owner_sub WHERE s.id = %s"""


class CopilotAccountNotFoundError(CredentialUnavailableError):
    """The requested account is not owned by the caller."""


class CopilotAccountConflictError(CredentialUnavailableError):
    """An explicit account/revision is required, or the supplied one is stale."""


class CopilotAccountInvalidError(CredentialUnavailableError):
    """Account management input does not satisfy the local contract."""


_PUBLIC_ERRORS = {
    CopilotAccountNotFoundError: "Copilot account was not found",
    CopilotAccountConflictError: "Copilot account changed; select the account and current revision explicitly",
    CopilotAccountInvalidError: "Invalid Copilot account request",
    CredentialUnavailableError: "Copilot account credential is unavailable",
}


def _sanitized(operation):
    @wraps(operation)
    def call(*args, **kwargs):
        error_type = CredentialUnavailableError
        try:
            return operation(*args, **kwargs)
        except (CopilotAccountNotFoundError, CopilotAccountConflictError, CopilotAccountInvalidError) as error:
            error_type = type(error)
        except Exception:
            # Database/JSON exceptions may contain credential parameters. Do
            # not chain them into a public error or retain them as its context.
            pass
        raise error_type(_PUBLIC_ERRORS[error_type])
    return call


def _identity(value):
    return isinstance(value, str) and bool(value) and value == value.strip() and value.isprintable()


def _encode(credential):
    return encrypt_secret(json.dumps({"copilot": {
        "version": 1, "principal_id": credential.principal_id,
        "revision": credential.revision, "kind": credential.kind.value,
        "token": credential.token, "expires_at": credential.expires_at,
    }}))


def _decode(row):
    if not row or row["layer"] != "copilot-cli" or row["provider"] != "github":
        raise CredentialUnavailableError()
    blob = json.loads(decrypt_secret(row["credential_data_enc"]))
    data = blob["copilot"]
    if (type(data) is not dict or type(data.get("version")) is not int
            or data["version"] != 1 or set(data) != {
                "version", "principal_id", "revision", "kind", "token", "expires_at",
            }):
        raise CredentialUnavailableError()
    kind = CredentialKind(data["kind"])
    if row["auth_type"] != _AUTH_TYPES[kind] or row["oauth_email"] != data["principal_id"]:
        raise CredentialUnavailableError()
    # Revisions generated by this store are UUIDs, never timestamps/counters.
    if str(uuid.UUID(data["revision"])) != data["revision"]:
        raise CredentialUnavailableError()
    return CopilotCredential(
        account_id=row["id"], principal_id=data["principal_id"], revision=data["revision"],
        kind=kind, token=data["token"], expires_at=data["expires_at"],
    )


@_sanitized
def create_account(owner_sub, principal_id, kind, token, expires_at,
                   use_personal=True, contribute_platform=False, label="") -> dict:
    """Create an explicitly owned account; shared contribution defaults off."""
    if (not _identity(owner_sub) or type(use_personal) is not bool
            or type(contribute_platform) is not bool or not isinstance(label, str)):
        raise CredentialUnavailableError()
    credential = CopilotCredential(
        account_id=str(uuid.uuid4()), principal_id=principal_id,
        revision=str(uuid.uuid4()), kind=kind, token=token, expires_at=expires_at,
    )
    credential.ensure_usable(time.time())
    encrypted = _encode(credential)
    with get_conn() as conn:
        owner = conn.execute("SELECT role FROM users WHERE sub = %s FOR SHARE", (owner_sub,)).fetchone()
        if not owner or (contribute_platform and owner["role"] != "admin"):
            raise CredentialUnavailableError()
        now = _now()
        row = conn.execute(
            """INSERT INTO execution_layer_subscriptions
               (id, layer, provider, auth_type, owner_sub, use_personal,
                contribute_platform, label, credential_data_enc, oauth_email,
                active_sessions, status, created_at, updated_at)
               VALUES (%s, 'copilot-cli', 'github', %s, %s, %s, %s, %s, %s,
                       %s, 0, 'active', %s, %s) RETURNING *""",
            (credential.account_id, _AUTH_TYPES[kind], owner_sub, use_personal,
             contribute_platform, label, encrypted, principal_id, now, now),
        ).fetchone()
        conn.commit()
        return _row_to_dict(row)


@_sanitized
def read_credential(account_id, scope, min_runway=0) -> CopilotCredential:
    """Read one selected account with current scope and owner eligibility."""
    if not _identity(account_id) or type(scope) is not CopilotAccountScope:
        raise CredentialUnavailableError()
    with get_conn() as conn:
        row = conn.execute(_SELECT, (account_id,)).fetchone()
        if not row or row["status"] != "active":
            raise CredentialUnavailableError()
        if scope.kind is AccountScopeKind.PERSONAL:
            allowed = row["owner_sub"] == scope.user_sub and row["use_personal"] is True
        else:
            allowed = row["contribute_platform"] is True and row["owner_role"] == "admin"
        if not allowed:
            raise CredentialUnavailableError()
        credential = _decode(row)
        credential.ensure_usable(time.time(), min_runway)
        return credential


@_sanitized
def replace_credential(account_id, owner_sub, expected_revision, principal_id,
                       kind, token, expires_at) -> CopilotCredential:
    """Owner-only compare-and-swap refresh; never revive a disabled account."""
    if not _identity(owner_sub) or not _identity(account_id):
        raise CredentialUnavailableError()
    with get_conn() as conn:
        row = conn.execute(_SELECT + " FOR UPDATE OF s", (account_id,)).fetchone()
        if not row or row["owner_sub"] != owner_sub:
            raise CredentialUnavailableError()
        old = _decode(row)
        if (old.revision != expected_revision or old.principal_id != principal_id
                or old.kind is not kind):
            raise CredentialUnavailableError()
        credential = CopilotCredential(
            account_id=account_id, principal_id=principal_id, revision=str(uuid.uuid4()),
            kind=kind, token=token, expires_at=expires_at,
        )
        credential.ensure_usable(time.time())
        conn.execute(
            """UPDATE execution_layer_subscriptions
               SET credential_data_enc = %s, updated_at = %s WHERE id = %s""",
            (_encode(credential), _now(), account_id),
        )
        conn.commit()
        return credential


def _validate_owner(owner_sub):
    if not _identity(owner_sub):
        raise CopilotAccountInvalidError()


def _validate_label(label):
    if not isinstance(label, str) or len(label) > 200 or (label and not label.isprintable()):
        raise CopilotAccountInvalidError()


def _lock_owner(conn, owner_sub):
    # All managed writes for one owner take this lock before the account lock.
    # This serializes duplicate connects and races with owner deletion/demotion.
    owner = conn.execute("SELECT role FROM users WHERE sub = %s FOR UPDATE", (owner_sub,)).fetchone()
    if not owner:
        raise CopilotAccountNotFoundError()
    return owner


def _owned_row(conn, account_id, owner_sub, *, lock=False):
    if not _identity(account_id):
        raise CopilotAccountInvalidError()
    row = conn.execute(
        _SELECT + " AND s.owner_sub = %s AND s.layer = 'copilot-cli' AND s.provider = 'github'"
        " AND s.auth_type IN ('copilot_user_token', 'copilot_installation_token')"
        + (" FOR UPDATE OF s" if lock else ""), (account_id, owner_sub),
    ).fetchone()
    if not row:
        raise CopilotAccountNotFoundError()
    return row


def _projection(row):
    # Decode shape/identity without checking lifetime: expired accounts must
    # remain visible so their owner can explicitly reconnect or remove them.
    credential = _decode(row)
    return {
        "id": row["id"], "label": row["label"], "principal_id": credential.principal_id,
        "revision": credential.revision, "auth_kind": credential.kind.value,
        "status": row["status"], "use_personal": row["use_personal"],
        "contribute_platform": row["contribute_platform"], "expires_at": credential.expires_at,
    }


@_sanitized
def get_owned_account(account_id, owner_sub) -> dict:
    _validate_owner(owner_sub)
    with get_conn() as conn:
        return _projection(_owned_row(conn, account_id, owner_sub))


@_sanitized
def list_owned_accounts(owner_sub) -> list[dict]:
    _validate_owner(owner_sub)
    with get_conn() as conn:
        rows = conn.execute(
            """SELECT s.* FROM execution_layer_subscriptions s
               JOIN users u ON u.sub = s.owner_sub
               WHERE s.owner_sub = %s AND s.layer = 'copilot-cli' AND s.provider = 'github'
               AND s.auth_type IN ('copilot_user_token', 'copilot_installation_token')
               ORDER BY s.created_at, s.id""", (owner_sub,),
        ).fetchall()
        return [_projection(row) for row in rows]


@_sanitized
def connect_user_account(owner_sub, principal_id, token, expires_at, label=None,
                         account_id=None, expected_revision=None) -> dict:
    """Persist a caller-verified GitHub user identity, without guessing a replacement.

    Supplying an account ID always means replace that existing account. Missing
    or deleted targets never fall through to creation; flags/status are retained.
    """
    _validate_owner(owner_sub)
    if label is not None:
        _validate_label(label)
    if (not isinstance(principal_id, str)
            or re.fullmatch(r"github:user:[1-9][0-9]*", principal_id) is None):
        raise CopilotAccountInvalidError()
    if (account_id is None) != (expected_revision is None):
        raise CopilotAccountInvalidError()
    if account_id is not None and (not _identity(account_id) or not _identity(expected_revision)):
        raise CopilotAccountInvalidError()
    invalid = False
    try:
        credential = CopilotCredential(
            account_id=account_id if account_id is not None else str(uuid.uuid4()),
            principal_id=principal_id, revision=str(uuid.uuid4()), kind=CredentialKind.USER_TOKEN,
            token=token, expires_at=expires_at,
        )
        credential.ensure_usable(time.time())
    except CredentialUnavailableError:
        invalid = True
    if invalid:
        raise CopilotAccountInvalidError()
    with get_conn() as conn:
        _lock_owner(conn, owner_sub)
        if account_id is not None:
            row = _owned_row(conn, account_id, owner_sub, lock=True)
            old = _decode(row)
            if (old.kind is not CredentialKind.USER_TOKEN or old.principal_id != principal_id
                    or old.revision != expected_revision):
                raise CopilotAccountConflictError()
            row = conn.execute(
                """UPDATE execution_layer_subscriptions SET credential_data_enc = %s,
                   label = %s, updated_at = %s WHERE id = %s RETURNING *""",
                (_encode(credential), row["label"] if label is None else label, _now(), account_id),
            ).fetchone()
        else:
            existing = conn.execute(
                """SELECT id FROM execution_layer_subscriptions WHERE owner_sub = %s
                   AND layer = 'copilot-cli' AND provider = 'github'
                   AND auth_type = 'copilot_user_token' AND oauth_email = %s""",
                (owner_sub, principal_id),
            ).fetchone()
            if existing:
                raise CopilotAccountConflictError()
            now = _now()
            row = conn.execute(
                """INSERT INTO execution_layer_subscriptions
                   (id, layer, provider, auth_type, owner_sub, use_personal,
                    contribute_platform, label, credential_data_enc, oauth_email,
                    active_sessions, status, created_at, updated_at)
                   VALUES (%s, 'copilot-cli', 'github', 'copilot_user_token', %s,
                           TRUE, FALSE, %s, %s, %s, 0, 'active', %s, %s) RETURNING *""",
                (credential.account_id, owner_sub, label if label is not None else "",
                 _encode(credential), principal_id, now, now),
            ).fetchone()
        result = _projection(row)
        conn.commit()
        return result


@_sanitized
def update_owned_account(account_id, owner_sub, *, label=None, use_personal=None,
                         contribute_platform=None, status=None) -> dict:
    """Owner-scoped controls; shared contribution requires the owner's current admin role."""
    _validate_owner(owner_sub)
    if label is not None:
        _validate_label(label)
    if any(value is not None and type(value) is not bool for value in (use_personal, contribute_platform)):
        raise CopilotAccountInvalidError()
    if status is not None and status not in ("active", "disabled"):
        raise CopilotAccountInvalidError()
    with get_conn() as conn:
        owner = _lock_owner(conn, owner_sub)
        row = _owned_row(conn, account_id, owner_sub, lock=True)
        if contribute_platform is True and owner["role"] != "admin":
            raise CopilotAccountInvalidError()
        changes = {key: value for key, value in {
            "label": label, "use_personal": use_personal,
            "contribute_platform": contribute_platform, "status": status,
        }.items() if value is not None}
        if changes:
            assignments = ", ".join(f"{key} = %s" for key in changes)
            row = conn.execute(
                f"UPDATE execution_layer_subscriptions SET {assignments}, updated_at = %s WHERE id = %s RETURNING *",
                (*changes.values(), _now(), account_id),
            ).fetchone()
        result = _projection(row)
        conn.commit()
        return result


@_sanitized
def delete_owned_account(account_id, owner_sub) -> bool:
    _validate_owner(owner_sub)
    with get_conn() as conn:
        _lock_owner(conn, owner_sub)
        _owned_row(conn, account_id, owner_sub, lock=True)
        # Deletion remains possible for malformed/expired credential blobs.
        conn.execute("DELETE FROM execution_layer_subscriptions WHERE id = %s", (account_id,))
        conn.commit()
        return True
